### ISSUE TITLE
How to interpret Application and Container History plot ?

### ISSUE THREAD

**Issue by abhranilc** [apache/incubator-yunikorn-web#12]
I am testing yunikorn on a local setup on my mac using docker-for-desktop K8s.
The number of containers and applications plotted on the graph are not making sense to me.
<img width="1423" alt="pic0" src="https://user-images.githubusercontent.com/3633725/63510265-c3a95280-c4fb-11e9-8e2b-9f828832f65f.png">

**Comment by yangwwei** [comment]
Hi @abhranilc 

These history pages are mocked, we just haven't get there : )
@akhilpb001 do you have any bandwidth lately for this? Another thing, when apps/containers are 0, can we display an empty pie instead of just blank (might be more consistent)? 
Let me know your thoughts, thanks.

**Comment by akhilpb001** [comment]
@yangwwei Do we have real data from yunikorn so we can hook that up in UI?

**Comment by yangwwei** [comment]
Hello @abhranilc 

We do have those data, just need to expose them through rest-api so UI can fetch. Could you please suggest what kind of format you are expecting to render application/container history?

Thanks

**Comment by akhilpb001** [comment]
@yangwwei We need array of objects which contains value and secs/millisecs.
Ex: 
```
[
  {
     value: 20,
     time: 589393944
  },
  {
     value: 50,
     time: 5200473354
  }
]
```
The time could be in seconds or milliseconds and each value could be 1 hour apart (1 hour interval).

**Comment by yangwwei** [comment]
Thanks @abhranilc , let me create an issue in yunikorn-core to track this change. Will let you know once that is done.

**Comment by abhranilc** [comment]
@yangwwei the current representation on application/container history is fine. Once it starts reflecting real data, should be good

**Comment by yangwwei** [comment]
Sounds great, thanks @akhilpb001 !

**Comment by akhilpb001** [comment]
@yangwwei @sunilgovind When will #36 be merged? This api is required to fix this UI issue.

**Comment by akhilpb001** [comment]
This is blocked by https://github.com/cloudera/yunikorn-core/issues/36.

**Comment by wilfred-s** [comment]
Moved to jira YUNIKORN-8

https://issues.apache.org/jira/projects/YUNIKORN/issues/YUNIKORN-8
