### ISSUE TITLE
yunikorn-scheduler-web component start not normal

### ISSUE THREAD

**Issue by baikai** [apache/incubator-yunikorn-web#17]
Install yunikorn by helm charts, found yunikorn-scheduler-web component start not normal.
1 yunikorn-scheduler-web container running.
2 Check yunikorn-scheduler-web container logs by kubectl logs -f cli, and found no output.
3 Entry into yunikorn-scheduler-web container inside, and found  web code dir '/usr/uiapp' not exists in container.
(yunikorn-scheduler-web docker image id is: db65c385b2dc)

**Comment by yangwwei** [comment]
I just tried locally, it seems to work fine.

From the service page, I can go to the web UI: http://localhost:9889/dashboard

![Services_-_Kubernetes_Dashboard](https://user-images.githubusercontent.com/14214570/65329715-a0052500-dbeb-11e9-859f-96f09ad7ac9e.jpg)

the UI comes up

![Yunikorn_UI](https://user-images.githubusercontent.com/14214570/65329800-c7f48880-dbeb-11e9-9e99-483c299e80ca.jpg)

checking logs

```
➜  helm-charts git:(master) kubectl logs yunikorn-scheduler-7b7cd7d77c-p9qbh yunikorn-scheduler-web
192.168.65.3 - - [20/Sep/2019:13:10:50 +0000] "GET / HTTP/1.1" 200 1003 "http://localhost:8001/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:50 +0000] "GET /styles.24bdb19cbbd0d2253431.css HTTP/1.1" 200 60129 "http://localhost:9889/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:50 +0000] "GET /runtime.a66f828dca56eeb90e02.js HTTP/1.1" 200 1053 "http://localhost:9889/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:50 +0000] "GET /polyfills.a45719e04e0a2139ff57.js HTTP/1.1" 200 63246 "http://localhost:9889/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:50 +0000] "GET /main.0fa0b933a830670aaaa2.js HTTP/1.1" 200 1369755 "http://localhost:9889/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:52 +0000] "GET /assets/config/envconfig.json HTTP/1.1" 200 141 "http://localhost:9889/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:52 +0000] "GET /assets/images/logo.png HTTP/1.1" 200 1578 "http://localhost:9889/dashboard" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
192.168.65.3 - - [20/Sep/2019:13:10:54 +0000] "GET /favicon.ico HTTP/1.1" 200 1578 "http://localhost:9889/clusters/kubernetes/info" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
```
I am using docker image from: https://hub.docker.com/r/yunikorn/yunikorn-web/tags. It was not built from latest source, but I don't think we have any code-level changes so far.

**Comment by sunilgovind** [comment]
I just checked now and i was able to access
cud u pls share more errors if u have

**Comment by baikai** [comment]
thx @yangwwei  and @sunilgovind,
1 Check web container's log, no info or error:
![Uploading image.png…]()
2 Check web container inside, not found web code dir:
![Uploading image.png…]()
3 Which image you used in your local env?

**Comment by baikai** [comment]
![image](https://user-images.githubusercontent.com/3839050/65371032-e8771e00-dc91-11e9-8e3d-db9cf81f6f53.png)
![image](https://user-images.githubusercontent.com/3839050/65371034-f3ca4980-dc91-11e9-832d-9746f82cb4f3.png)

**Comment by yangwwei** [comment]
@akhilpb001 do you have any idea about what could happen here?
Appreciate if you can take a look, thx.

**Comment by baikai** [comment]
Sorry,  ui code located in /usr/share/nginx/html, not /usr/uiapp.
But I still cannot see any log output when container start.

**Comment by wilfred-s** [comment]
Lots has changed since the issue was logged, if the issue still exists please open it as a new jira:
https://issues.apache.org/jira/projects/YUNIKORN

github issues will no longer be used
